### ISSUE TITLE
Enum annotation for numbers won't be generated 

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#759] opened 2022-06-24 14:00 UTC
### URL Hash

#/sklearn/sklearn.preprocessing._data/normalize/axis

### Expected Annotation Type

`@enum`

### Expected Annotation Inputs

{0, 1}

**Comment by lars-reimann** [comment] 2022-06-24 18:33
Duplicate of https://github.com/lars-reimann/api-editor/issues/743.

**Closed by lars-reimann** 2022-06-24 18:33 UTC
Labels: bug, duplicate, missing annotation
