### ISSUE TITLE
1 and 1.0 are counted as different values

### ISSUE THREAD

**Issue by Masara** [lars-reimann/api-editor#867] opened 2022-07-01 12:42 UTC
### Describe the bug

The int 1 and the float 1.0 are being counted as different values

### To Reproduce

#/sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale

### Expected behavior

They should be counted as one value, since the values used are the same

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/2046129/176895553-7246427f-fe5f-4b28-a300-f04a2c26eaf9.png)

### Additional Context (optional)

API Data:
<details>
    <summary>Minimal API Data for `sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale`</summary>

```json5
{
    "schemaVersion": 1,
    "distribution": "scikit-learn",
    "package": "sklearn",
    "version": "1.1.1",
    "modules": [
        {
            "id": "sklearn/sklearn.gaussian_process.kernels",
            "name": "sklearn.gaussian_process.kernels",
            "imports": [
                {
                    "module": "math",
                    "alias": null
                },
                {
                    "module": "numpy",
                    "alias": "np"
                },
                {
                    "module": "warnings",
                    "alias": null
                }
            ],
            "from_imports": [
                {
                    "module": "abc",
                    "declaration": "ABCMeta",
                    "alias": null
                },
                {
                    "module": "abc",
                    "declaration": "abstractmethod",
                    "alias": null
                },
                {
                    "module": "collections",
                    "declaration": "namedtuple",
                    "alias": null
                },
                {
                    "module": "inspect",
                    "declaration": "signature",
                    "alias": null
                },
                {
                    "module": "scipy.spatial.distance",
                    "declaration": "cdist",
                    "alias": null
                },
                {
                    "module": "scipy.spatial.distance",
                    "declaration": "pdist",
                    "alias": null
                },
                {
                    "module": "scipy.spatial.distance",
                    "declaration": "squareform",
                    "alias": null
                },
                {
                    "module": "scipy.special",
                    "declaration": "gamma",
                    "alias": null
                },
                {
                    "module": "scipy.special",
                    "declaration": "kv",
                    "alias": null
                },
                {
                    "module": "sklearn.base",
                    "declaration": "clone",
                    "alias": null
                },
                {
                    "module": "sklearn.exceptions",
                    "declaration": "ConvergenceWarning",
                    "alias": null
                },
                {
                    "module": "sklearn.metrics.pairwise",
                    "declaration": "pairwise_kernels",
                    "alias": null
                },
                {
                    "module": "sklearn.utils.validation",
                    "declaration": "_num_samples",
                    "alias": null
                }
            ],
            "classes": [
                "sklearn/sklearn.gaussian_process.kernels/RBF"
            ],
            "functions": []
        }
    ],
    "classes": [
        {
            "id": "sklearn/sklearn.gaussian_process.kernels/RBF",
            "name": "RBF",
            "qname": "sklearn.gaussian_process.kernels.RBF",
            "decorators": [],
            "superclasses": [
                "StationaryKernelMixin",
                "NormalizedKernelMixin",
                "Kernel"
            ],
            "methods": [
                "sklearn/sklearn.gaussian_process.kernels/RBF/__init__"
            ],
            "is_public": true,
            "reexported_by": [],
            "description": "Radial-basis function kernel (aka squared-exponential kernel).\n\nThe RBF kernel is a stationary kernel. It is also known as the\n\"squared exponential\" kernel. It is parameterized by a length scale\nparameter :math:`l>0`, which can either be a scalar (isotropic variant\nof the kernel) or a vector with the same number of dimensions as the inputs\nX (anisotropic variant of the kernel). The kernel is given by:\n\n.. math::\nk(x_i, x_j) = \\exp\\left(- \\frac{d(x_i, x_j)^2}{2l^2} \\right)\n\nwhere :math:`l` is the length scale of the kernel and\n:math:`d(\\cdot,\\cdot)` is the Euclidean distance.\nFor advice on how to set the length scale parameter, see e.g. [1]_.\n\nThis kernel is infinitely differentiable, which implies that GPs with this\nkernel as covariance function have mean square derivatives of all orders,\nand are thus very smooth.\nSee [2]_, Chapter 4, Section 4.2, for further details of the RBF kernel.\n\nRead more in the :ref:`User Guide <gp_kernels>`.\n\n.. versionadded:: 0.18",
            "docstring": "Radial-basis function kernel (aka squared-exponential kernel).\n\nThe RBF kernel is a stationary kernel. It is also known as the\n\"squared exponential\" kernel. It is parameterized by a length scale\nparameter :math:`l>0`, which can either be a scalar (isotropic variant\nof the kernel) or a vector with the same number of dimensions as the inputs\nX (anisotropic variant of the kernel). The kernel is given by:\n\n.. math::\n    k(x_i, x_j) = \\exp\\left(- \\frac{d(x_i, x_j)^2}{2l^2} \\right)\n\nwhere :math:`l` is the length scale of the kernel and\n:math:`d(\\cdot,\\cdot)` is the Euclidean distance.\nFor advice on how to set the length scale parameter, see e.g. [1]_.\n\nThis kernel is infinitely differentiable, which implies that GPs with this\nkernel as covariance function have mean square derivatives of all orders,\nand are thus very smooth.\nSee [2]_, Chapter 4, Section 4.2, for further details of the RBF kernel.\n\nRead more in the :ref:`User Guide <gp_kernels>`.\n\n.. versionadded:: 0.18\n\nParameters\n----------\nlength_scale : float or ndarray of shape (n_features,), default=1.0\n    The length scale of the kernel. If a float, an isotropic kernel is\n    used. If an array, an anisotropic kernel is used where each dimension\n    of l defines the length-scale of the respective feature dimension.\n\nlength_scale_bounds : pair of floats >= 0 or \"fixed\", default=(1e-5, 1e5)\n    The lower and upper bound on 'length_scale'.\n    If set to \"fixed\", 'length_scale' cannot be changed during\n    hyperparameter tuning.\n\nReferences\n----------\n.. [1] `David Duvenaud (2014). \"The Kernel Cookbook:\n    Advice on Covariance functions\".\n    <https://www.cs.toronto.edu/~duvenaud/cookbook/>`_\n\n.. [2] `Carl Edward Rasmussen, Christopher K. I. Williams (2006).\n    \"Gaussian Processes for Machine Learning\". The MIT Press.\n    <http://www.gaussianprocess.org/gpml/>`_\n\nExamples\n--------\n>>> from sklearn.datasets import load_iris\n>>> from sklearn.gaussian_process import GaussianProcessClassifier\n>>> from sklearn.gaussian_process.kernels import RBF\n>>> X, y = load_iris(return_X_y=True)\n>>> kernel = 1.0 * RBF(1.0)\n>>> gpc = GaussianProcessClassifier(kernel=kernel,\n...         random_state=0).fit(X, y)\n>>> gpc.score(X, y)\n0.9866...\n>>> gpc.predict_proba(X[:2,:])\narray([[0.8354..., 0.03228..., 0.1322...],\n       [0.7906..., 0.0652..., 0.1441...]])"
        }
    ],
    "functions": [
        {
            "id": "sklearn/sklearn.gaussian_process.kernels/RBF/__init__",
            "name": "__init__",
            "qname": "sklearn.gaussian_process.kernels.RBF.__init__",
            "decorators": [],
            "parameters": [
                {
                    "id": "sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale",
                    "name": "length_scale",
                    "qname": "sklearn.gaussian_process.kernels.RBF.__init__.length_scale",
                    "default_value": "1.0",
                    "assigned_by": "POSITION_OR_NAME",
                    "is_public": true,
                    "docstring": {
                        "type": "float or ndarray of shape (n_features,)",
                        "description": "The length scale of the kernel. If a float, an isotropic kernel is\nused. If an array, an anisotropic kernel is used where each dimension\nof l defines the length-scale of the respective feature dimension."
                    },
                    "type": {}
                }
            ],
            "results": [],
            "is_public": true,
            "reexported_by": [],
            "description": "Radial-basis function kernel (aka squared-exponential kernel).\n\nThe RBF kernel is a stationary kernel. It is also known as the\n\"squared exponential\" kernel. It is parameterized by a length scale\nparameter :math:`l>0`, which can either be a scalar (isotropic variant\nof the kernel) or a vector with the same number of dimensions as the inputs\nX (anisotropic variant of the kernel). The kernel is given by:\n\n.. math::\nk(x_i, x_j) = \\exp\\left(- \\frac{d(x_i, x_j)^2}{2l^2} \\right)\n\nwhere :math:`l` is the length scale of the kernel and\n:math:`d(\\cdot,\\cdot)` is the Euclidean distance.\nFor advice on how to set the length scale parameter, see e.g. [1]_.\n\nThis kernel is infinitely differentiable, which implies that GPs with this\nkernel as covariance function have mean square derivatives of all orders,\nand are thus very smooth.\nSee [2]_, Chapter 4, Section 4.2, for further details of the RBF kernel.\n\nRead more in the :ref:`User Guide <gp_kernels>`.\n\n.. versionadded:: 0.18",
            "docstring": ""
        }
    ]
}
```
</details>

Usages data:
<details>
    <summary>Minimal Usage Store for `sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale`</summary>

```json5
{
    "schemaVersion": 1,
    "module_counts": {
        "sklearn/sklearn.gaussian_process.kernels": 21
    },
    "class_counts": {
        "sklearn/sklearn.gaussian_process.kernels/RBF": 13
    },
    "function_counts": {
        "sklearn/sklearn.gaussian_process.kernels/RBF/__init__": 13
    },
    "parameter_counts": {
        "sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale": 12
    },
    "value_counts": {
        "sklearn/sklearn.gaussian_process.kernels/RBF/__init__/length_scale": {
            "1": 2,
            "1.0": 8,
            "[1.0, 1.0, 1.0, 1.0]": 2,
            "0.0001": 1
        }
    }
}
```
</details>

**Comment by lars-reimann** [comment] 2022-07-01 12:47
Duplicate of https://github.com/lars-reimann/api-editor/issues/868.

**Closed by lars-reimann** 2022-07-01 12:47 UTC
Labels: bug, duplicate
