### ISSUE TITLE
Support for Links in the documentation

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#766] opened 2022-06-24 14:23 UTC
### Is your feature request related to a problem?

It's confusing reading somthing like ":class:`~sklearn.pipeline.Pipeline`".

### Desired solution

Replace ":class:`NAME_TO_CLASS`" with a link to #/PATH/TO/CLASS so that the upper example would lead to the Pipeline class.

**Comment by lars-reimann** [comment] 2022-06-24 15:59
Duplicate of #95.

**Closed** 2022-06-24 16:18 UTC
Labels: duplicate, enhancement
