### ISSUE TITLE
Enum where no annotation should be generated (because it is a Union-Type)

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#754] opened 2022-06-24 13:45 UTC
### URL Hash

#/sklearn/sklearn.metrics._classification/f1_score/average

### Actual Annotation Type

`@enum`

### Actual Annotation Inputs

{'micro', 'macro', 'samples', 'weighted', 'binary'} or None, default='binary'

### Expected Annotation Type

No annotation

### Expected Annotation Inputs

n/a

**Comment by lars-reimann** [comment] 2022-06-24 16:43
Duplicate of https://github.com/lars-reimann/api-editor/issues/762.

**Closed by lars-reimann** 2022-06-24 16:43 UTC
Labels: bug, duplicate, wrong annotation
