### ISSUE TITLE
Define an Enum as part of a Union Type

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#762] opened 2022-06-24 14:11 UTC
### Is your feature request related to a problem?

There are quite a few parameters, that accept an enum OR some other type of value (like int or float, but also stuff like lists, dictionaries, or lists of dictionaries).

### Desired solution

There needs to be a way to deal with these types of parameters. Seems to be a bit out of scope to think of a solution right now.

### Additional Context (optional)

Examples:
- `#/sklearn/sklearn.metrics._classification/f1_score/average`

**Comment by lars-reimann** [comment] 2022-06-24 19:15
Duplicate of https://github.com/lars-reimann/api-editor/issues/762.

**Closed by lars-reimann** 2022-06-24 19:15 UTC
Labels: duplicate, enhancement
